### ISSUE TITLE
add alertmanager chart

### ISSUE THREAD

**Issue by naseemkullah** [scottrigby/prometheus-helm-charts#17]
If desired, please incorporate https://github.com/naseemkullah/naseem-charts/tree/master/charts/alertmanager to the repo, we could swap it in the (vanilla) prometheus chart. cc @zanhsieh

**Comment by scottrigby** [comment]
Great! Would you be able to write up some instructions on how to do the swap?

**Comment by naseemkullah** [comment]
Sure thing, it would be similar to what was done here for kube-state-metrics: https://github.com/helm/charts/pull/21148/files

basically remove all alertmanager related templates and values from the chart and add a dependency, I'll make a PR!

**Comment by scottrigby** [comment]
@naseemkullah that would be great 😄 

I'm trying to think about the order here... maybe it would make sense to make the PR against this branch for now? https://github.com/scottrigby/prometheus-helm-charts/pull/14

If you have feedback on the changes I made to the `prometheus` chart in that PR beforehand, please feel free. Otherwise please just make your changes against that branch. Thanks!

**Comment by naseemkullah** [comment]
Sounds good, re: prometheus changes, as we extract charts from the monolithic one we may no longer have much use for the subfolders based on resource type. Another chart I could see extracted is the node-exporter

**Comment by naseemkullah** [comment]
uhh, on second thought this may be too disruptive, if prometheus community do not have qualms with alertmanager being embedded, let's just leave it as is for now.. my bad.
